
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocdd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Naomi-org/Argocd-test.git
  password: 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
  username: TekangBush